version: '1.0'

services:
  load_balancer:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates

  container1:
    image: paulbouwer/hello-kubernetes:1.0

  container2:
    image: paulbouwer/hello-kubernetes:1.0
  
  container3:
    image: paulbouwer/hello-kubernetes:1.0
  
  container4:
    image: paulbouwer/hello-kubernetes:1.0
  
  container5:
    image: paulbouwer/hello-kubernetes:1.0
  
  #container6:
   # image: paulbouwer/hello-kubernetes:1.0

  #container7:
    #image: paulbouwer/hello-kubernetes:1.0
  
  #container8:
   # image: paulbouwer/hello-kubernetes:1.0
  
  #container9:
   # image: paulbouwer/hello-kubernetes:1.0
  
 # container10:
  #  image: paulbouwer/hello-kubernetes:1.0  
